version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  redis:
    image: redis:6.2.6
    volumes:
      - redis-volume:/data
    ports:
      - 6379:6379

volumes:
  db-volume:
  redis-volume:
